Models/ErrorViewModel.cs
namespace TareaClinicaProgra4.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Virus.cs
namespace TareaClinicaProgra4.Models;

public class Virus
{
    private int id;
    private String nombre;
    private DateTime fecha;
    private int mortalidad;
    private int contagio;
    private String peligrosidad;
    public Virus(int id, string nombre, DateTime fecha, int mortalidad, int contagio)
    {
        this.id = id;
        this.nombre = nombre;
        this.fecha = fecha;
        this.mortalidad = mortalidad;
        this.contagio = contagio;
        this.peligrosidad = AsignarPeligrosidad(mortalidad, contagio);
    }

    public Virus()
    {
        this.id = 0;
        this.nombre = "";
        this.mortalidad = 0;
        this.contagio = 0;
        this.peligrosidad = AsignarPeligrosidad(this.mortalidad, this.contagio);
        
    }
    public int Id { get => id; set => id = value; }
    public string Nombre { get => nombre; set => nombre = value; }
    public DateTime Fecha { get => fecha; set => fecha = value; }
    public int Mortalidad { get => mortalidad; set => mortalidad = value; }
    public int Contagio { get => contagio; set => contagio = value; }
    public string Peligrosidad { get => peligrosidad; set => peligrosidad = value; }

    public string AsignarPeligrosidad(int mortalidad, int contagio)
    {
        int indicePeligrosidad = mortalidad * contagio;
        if (indicePeligrosidad < 30 && indicePeligrosidad >= 1)
        {
            return "Bajo";
        }

        if (indicePeligrosidad <= 65 && indicePeligrosidad >= 30)
        {
            return "Medio";
        }
        if (indicePeligrosidad > 65)
        {
            return "Alto";
        }

        return "Sin peligro alguno";
    }
    
    
    
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TareaClinicaProgra4.Models;

namespace TareaClinicaProgra4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/VirusController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TareaClinicaProgra4.Models;
using TareaClinicaProgra4.Service;


namespace TareaClinicaProgra4.Controllers
{
    public class VirusController : Controller
    {
        private Services sv;

        public VirusController()
        {
            sv = new Services();
        }
        // GET: VirusController
        public ActionResult Index()
        {
            var model = sv.MostrarViruses();
            return View(model);
        }

        // GET: VirusController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VirusController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Virus model)
        {
            try
            {
                if (ModelState.IsValid) { 
                    sv.AgregarVirus(model);
                    return RedirectToAction(nameof(Index));
                }   
            }
            catch
            {
               
            }

            return View();
        }


        // GET: VirusController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var model = sv.BuscarVirus(id);
                sv.EliminarVirus(model);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
            return View();
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = sv.BuscarVirus(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Virus model)
        {
            try
            {
                sv.EditVirus(model);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine("kaput en edit" + e.Message);
            }
            return View();
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TareaClinicaProgra4</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TareaClinicaProgra4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TareaClinicaProgra4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Virus" asp-action="Index">Index de Viruses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TareaClinicaProgra4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Virus/Create.cshtml
@model TareaClinicaProgra4.Models.Virus

@{
    ViewData["Title"] = "Create";
}

<h1>Registrar</h1>

<h4>Virus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mortalidad" class="control-label"></label><br/>
                <select asp-for="Mortalidad" class="form-control">
                    @for(int i = 1;i < 11; i++)
                    {
                        <option value=@i.ToString()>@i</option>
                    }
                </select>
                
                
                
                
                <span asp-validation-for="Mortalidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contagio" class="control-label"></label><br>
                <label>@Html.RadioButton("Contagio",1)1</label>
                <label>@Html.RadioButton("Contagio",2)2</label>
                <label>@Html.RadioButton("Contagio",3)3</label>
                <label>@Html.RadioButton("Contagio",4)4</label>
                <label>@Html.RadioButton("Contagio",5)5</label>
                <label>@Html.RadioButton("Contagio",6)6</label>
                <label>@Html.RadioButton("Contagio",7)7</label>
                <label>@Html.RadioButton("Contagio",8)8</label>
                <label>@Html.RadioButton("Contagio",9)9</label>
                <label>@Html.RadioButton("Contagio",10)10</label>
                <span asp-validation-for="Contagio" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a el registro</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Virus/Delete.cshtml
@model TareaClinicaProgra4.Models.Virus

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Virus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mortalidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mortalidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contagio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contagio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Virus/Details.cshtml
@model TareaClinicaProgra4.Models.Virus

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Virus</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mortalidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mortalidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contagio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contagio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/Virus/Edit.cshtml
@model TareaClinicaProgra4.Models.Virus

@{
    ViewData["Title"] = "Edit";
}

<h4>Virus</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mortalidad" class="control-label"></label>
                <input asp-for="Mortalidad" class="form-control" />
                <span asp-validation-for="Mortalidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contagio" class="control-label"></label>
                <input asp-for="Contagio" class="form-control" />
                <span asp-validation-for="Contagio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Virus/Index.cshtml
@model IEnumerable<TareaClinicaProgra4.Models.Virus>

@{
    ViewData["Title"] = "Index";
}
<h1>Index</h1>
<p>
    <a asp-action="Create">Registrar Virus</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mortalidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contagio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Peligrosidad)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem=>item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mortalidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contagio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Peligrosidad)
            </td>
            <td>
                <a asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a>
            </td>
        </tr>
}
    </tbody>
</table>